### ISSUE TITLE
is it possible work in object detection？

### ISSUE THREAD

**Issue by meituan-gengyifei** [OscarXZQ/weight-selection#3]
from your work, may it work in classification task.but i wanna use it in object detection task. is it work if i wanna finetune backbone in object detection?

**Comment by OscarXZQ** [comment]
Hi,

For object detection, the common approach is to use a pretrained backbone. If a pretrained backbone were available, I would 
 still recommend using the pretrained backbone. In other cases, although not experimented, I anticipate that weight selection would serve as a good way for initialization on object detection.
